############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

############################################################
#
# Data Source Config
#
############################################################
spring:
  profiles:
    active: dev
  datasource:                                         # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000
      max-request-size: 512000

############################################################
#
# mybatis Config
#
############################################################
mybatis:
  type-aliases-package: us.supercheng.pojo      # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

mapper:
  mappers: us.supercheng.mymapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  auto-dialect: mysql
  support-methods-arguments: true
