############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8090

############################################################
#
# Data Source Config
#
############################################################
spring:
  datasource:                                         # 数据源的相关配置
    url: jdbc:mysql://192.168.31.46:3306/foodie_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: abc123456
  redis:
    password: moka_cheng
    # Standalone
    database: 0
    host: 192.168.31.46

    # Cluster
    # cluster:
    #  nodes: 192.168.31.152:6379,192.168.31.159:6379,192.168.31.184:6379,192.168.31.199:6379,192.168.31.206:6379,192.168.31.213:6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl